In [1]:
import numpy as np


In [2]:
np.linspace(0,1,12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [81]:
# 创建一个全为0的10x10数组
arr = np.zeros((10, 10))

# 设置矩阵边界为1
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1

print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [82]:
arr[arr % 2 != 0] = -1

print(arr)

[[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]


In [83]:
# 创建一个多维随机数组，范围0到12，6个元素，两行3列
random_array = np.random.randint(0, 12, size=(2, 3))
print(random_array)

# 打印数组所占的内存大小
print(f"数组所占内存大小：{random_array.nbytes}bytes")

# 打印数组根据第一列进行排序后的结果
sorted_array = random_array[random_array[:,0].argsort()]
print("根据第一列排序后的数组：")
print(sorted_array)

# 从数组中找出与给定值5最接近的值
given_value = 5
closest_value = random_array.flat[np.abs(random_array - given_value).argmin()]
print("与给定值5最接近的值：", closest_value)


[[5 9 0]
 [1 0 4]]
数组所占内存大小：24bytes
根据第一列排序后的数组：
[[1 0 4]
 [5 9 0]]
与给定值5最接近的值： 5


In [8]:
# 创建值为0到9的ndarray数组，指定为int8类型
arr = np.arange(10, dtype=np.int8)
print("原始数组：")
print(arr)

# 将数组类型改为布尔类型
bool_arr = arr.astype(bool)
print("布尔类型数组：")
print(bool_arr)

# 将数组类型改为float16类型
float_arr = arr.astype(np.float16)
print("float16类型数组：")
print(float_arr)


原始数组：
[0 1 2 3 4 5 6 7 8 9]
布尔类型数组：
[False  True  True  True  True  True  True  True  True  True]
float16类型数组：
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [86]:
# 数据
data = [3.0833, 2.7, 3.0833, 2.5, 2.75, 3.5, 3.9167, 42, 36, 0.75]

# 将数据列表转换为 NumPy 数组
arr = np.array(data)

# 使用 np.isin() 函数检查数组中是否包含指定的值
mask = np.isin(arr, [2.7, 42, 36])

print(arr[mask])

[ 2.7 42.  36. ]


In [11]:
arr = np.array([-3.2, 53, -3.6, 68, -4.5, 6.8571, -1.56, 8.4, -7])

print(f"数组中元素的绝对值：{np.abs(arr)}")
print(f"数组中元素的四舍五入值：{np.round(arr)}")
print(f"数组中的最大值：{np.max(arr)}")
print(f"数组中的最小值：{np.min(arr)}")


数组中元素的绝对值：[ 3.2    53.      3.6    68.      4.5     6.8571  1.56    8.4     7.    ]
数组中元素的四舍五入值：[-3. 53. -4. 68. -4.  7. -2.  8. -7.]
数组中的最大值：68.0
数组中的最小值：-7.0


In [17]:
A = np.ones(3) * 1
B = np.ones(3) * 2

# 初始化一个数组用于存放结果
result = np.empty(3)

np.divide(np.add(A, B), np.subtract(A, B))  
result

array([-3., -3., -3.])

In [100]:
radii = np.arange(1, 31)

areas = np.round(np.pi * radii**2, 2)

print(areas)

[   3.14   12.57   28.27   50.27   78.54  113.1   153.94  201.06  254.47
  314.16  380.13  452.39  530.93  615.75  706.86  804.25  907.92 1017.88
 1134.11 1256.64 1385.44 1520.53 1661.9  1809.56 1963.5  2123.72 2290.22
 2463.01 2642.08 2827.43]


In [23]:
np.random.seed(2023)
arr = np.random.randint(0, 100, 1000)

print(f"数学成绩大于60的学生人数：{np.sum(arr > 60)}")


数学成绩大于60的学生人数：401


In [25]:
height = np.array([1.73, 1.86, 1.56, 1.69, 1.53, 1.89, 1.87, 1.53, 1.66, 1.53])
weight = np.array([51, 64, 75, 58, 67, 59, 62, 70, 62, 59])

# 计算BMI
bmi = weight / height ** 2

# 输出BMI的排序结果
sorted_bmi = bmi[np.argsort(bmi)]
print(f"BMI排序结果：\n{sorted_bmi}")

# 统计BMI大于正常(>24)的元素数量
num_bmi_above_24 = np.sum(bmi > 24)
print(f"BMI大于正常的元素数量：{num_bmi_above_24}")

BMI排序结果：
[16.51689482 17.04032878 17.72998942 18.49924847 20.30741221 22.4996371
 25.20398137 28.62147037 29.90302875 30.81854043]
BMI大于正常的元素数量：4


In [107]:
# 定义dtype结构
color_dtype = np.dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1')])

input_colors = [(254, 253, 252), (0, 0, 0), (255, 255, 255)]

output_array = np.array(input_colors, dtype=color_dtype)
output_array


array([(254, 253, 252), (  0,   0,   0), (255, 255, 255)],
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1')])

In [90]:
# 创建棋盘形状数组
chessboard = np.zeros((8, 8), dtype=int)
chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1

print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [91]:
np.random.seed(123)
n = np.random.randint(0, 10, (3, 4))

sorted_array = n[n[:, 1].argsort()]

print(sorted_array)


[[0 1 9 0]
 [2 2 6 1]
 [3 9 6 1]]


In [37]:
arr = np.arange(9).reshape(3, 3)

print("源数组：")
print(arr)

# 交换第一列和第二列
arr[:, [0, 1]] = arr[:, [1, 0]]

print("交换第一列和第二列后的数组：")
print(arr)

源数组：
[[0 1 2]
 [3 4 5]
 [6 7 8]]
交换第一列和第二列后的数组：
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [92]:
np.random.seed(100)
arr = np.random.uniform(1, 50, 20)

# 获取前5个最大值的索引
max_indices = np.argsort(arr)[-5:]

print(arr[max_indices])

[40.99501269 41.466785   42.39403048 44.67477576 48.95256545]


In [44]:
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))

unique_counts = np.apply_along_axis(lambda row : len(set(row)), axis=1, arr=arr)

print(unique_counts)

[7 7 5 7 7 8]


In [57]:
A = np.arange(1, 5)
B = np.arange(3, 7)

# 设置自定义的绝对容差和相对容差
custom_atol = 1
custom_rtol = 0.1

result = np.allclose(A, B, atol=custom_atol, rtol=custom_rtol)

print(result)

False


In [80]:
arr = np.random.randint(0, 2, (3, 10))
print(arr)
# 检查每列是否存在非零元素
print(np.all(arr == 0, axis=0))

[[0 1 0 1 0 1 1 0 0 0]
 [0 0 1 1 0 1 0 0 0 0]
 [0 0 1 1 1 1 0 0 0 1]]
[ True False False False False False False  True  True False]


In [93]:
arr = np.array([[1,8,2,4],
                [4,5,1,3]])

# 默认按最后一个轴排序，这里按行排序
np.sort(arr)

# 轴设为0，即按列排序
np.sort(arr,axis=0)

# 轴设为1，即按行排序
np.sort(arr,axis=1)

array([[1, 2, 4, 8],
       [1, 3, 4, 5]])

In [94]:
# 自定义字段类型
dtype = [('Name', 'S10'), ('Height', float), ('Age', int)]
# 各字段值
values = [('Li', 1.8, 41), ('Wang', 1.9, 38),('Duan', 1.7, 38)]
# 创建数组
arr = np.array(values, dtype=dtype)
arr

array([(b'Li', 1.8, 41), (b'Wang', 1.9, 38), (b'Duan', 1.7, 38)],
      dtype=[('Name', 'S10'), ('Height', '<f8'), ('Age', '<i4')])

In [95]:
# 按照属性Height进行排序,此时参数为字符串          
np.sort(arr, order=['Height'])     

# 先按照属性Age排序,如果Age相等，再按照Height排序，此时参数为列表     
np.sort(arr, order=['Age', 'Height']) 

array([(b'Duan', 1.7, 38), (b'Wang', 1.9, 38), (b'Li', 1.8, 41)],
      dtype=[('Name', 'S10'), ('Height', '<f8'), ('Age', '<i4')])

In [96]:
arr = np.array([3, 1, 2])

# 获取排序后的索引
np.argsort(arr)

array([1, 2, 0], dtype=int64)

In [97]:
arr = np.array([[0, 3], [2, 2]])

# 默认按照最后一个轴进行排序，即行排序
# 获取排序后的索引
np.argsort(arr)

array([[0, 1],
       [0, 1]], dtype=int64)

In [98]:
# 英语成绩
english = [90,85,95,80]
# 数学成绩
math = [80,95,90,85]
# 总成绩
total = [170,170,185,165]

# 排序，获取索引
'''
先按总成绩total进行排序，
再按数学成绩math进行排序，
最后按英语成绩进行排序。
可以看到total里有两个170，
这时候就按下一级math排序，
最后获取排序后的索引
'''
np.lexsort((english, math, total))

array([3, 0, 1, 2], dtype=int64)

In [99]:
# 也可以直接传入数组
score = np.array([[90,85,95,80],[80,95,90,85],[170,170,185,165]])

np.lexsort(score)

array([3, 0, 1, 2], dtype=int64)